-- 코드를 입력하세요
SELECT TO_CHAR(A.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
        ,A.PRODUCT_ID
        ,A.USER_ID
        ,A.SALES_AMOUNT
   
FROM (
    SELECT SALES_DATE
        ,PRODUCT_ID	
        ,USER_ID	
        ,SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'MM') = '03'
    
    UNION ALL
    
    SELECT SALES_DATE
        ,PRODUCT_ID	
        ,NULL AS USER_ID
        ,SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE TO_CHAR(SALES_DATE, 'MM') = '03'    
    ) A

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;