-- 코드를 입력하세요
SELECT  C.CAR_ID 
        ,C.CAR_TYPE
        ,C.DAILY_FEE*30*(1-DISCOUNT_RATE*0.01) FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND D.DURATION_TYPE = '30일 이상'
    AND C.CAR_ID NOT IN (
                            SELECT CAR_ID
                            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                            WHERE TO_DATE('2022-11-01', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
                                OR TO_DATE('2022-11-30', 'YYYY-MM-DD') BETWEEN START_DATE AND END_DATE                                 )
    AND C.DAILY_FEE*30*(1-DISCOUNT_RATE*0.01) BETWEEN 500000 AND 2000001
GROUP BY C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE*30*(1-DISCOUNT_RATE*0.01)
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;