-- 2021년에 가입한 전체 회원들 중 
-- 상품을 구매한 회원수,
-- 상품을 구매한 회원의 비율
-- = 2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수

-- 년, 월 별로 출력 GROUP BY EXTRACT(YEAR FROM JOINED), EXTRACT(MONTH FROM JOINED)

-- 상품을 구매한 회원의 비율은 소수점 두번째자리에서 반올림
-- 년을 기준으로 ASC, 월을 기준으로 ASC

SELECT
    EXTRACT(YEAR FROM O.SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT O.USER_ID) * 1.0 / 
        (SELECT COUNT(*) FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = 2021),
        1
    ) AS PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_INFO U
    ON U.USER_ID = O.USER_ID
WHERE EXTRACT(YEAR FROM U.JOINED) = 2021
GROUP BY EXTRACT(YEAR FROM O.SALES_DATE), EXTRACT(MONTH FROM O.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC;
